"use client";

/**
 * Renders a Matplotlib/Seaborn chart produced by the Django backend.
 *
 * These endpoints require the Authorization header, and an <img src> cannot
 * send one, so the PNG is fetched as a blob and handed to the DOM as an object
 * URL. The URL is revoked on unmount and on every refetch, otherwise each theme
 * switch would leak a few hundred KB.
 */

import { useCallback, useEffect, useRef, useState } from "react";

import { api } from "@/lib/api";
import { useTheme } from "@/components/ThemeProvider";
import { Button, Skeleton, cx } from "@/components/ui/Primitives";
import { AlertIcon, DownloadIcon, RefreshIcon } from "@/components/ui/Icons";

export default function PythonChart({ slug, title, description, library, height = 340 }) {
  const { isDark } = useTheme();
  const [url, setUrl] = useState(null);
  const [state, setState] = useState("loading");
  const [error, setError] = useState("");
  const objectUrl = useRef(null);

  const release = useCallback(() => {
    if (objectUrl.current) {
      URL.revokeObjectURL(objectUrl.current);
      objectUrl.current = null;
    }
  }, []);

  const fetchChart = useCallback(async () => {
    setState("loading");
    setError("");
    try {
      const blob = await api.analytics.chartBlob(slug, isDark ? "dark" : "light");
      release();
      const next = URL.createObjectURL(blob);
      objectUrl.current = next;
      setUrl(next);
      setState("ready");
    } catch (caught) {
      setError(caught.message || "Could not render this chart.");
      setState("error");
    }
  }, [slug, isDark, release]);

  // Deferred by a microtask so the loading/ready state updates happen in a
  // callback instead of synchronously inside the effect body.
  useEffect(() => {
    let cancelled = false;
    Promise.resolve().then(() => {
      if (!cancelled) fetchChart();
    });
    return () => {
      cancelled = true;
      release();
    };
  }, [fetchChart, release]);

  return (
    <div className="flex h-full flex-col">
      <div className="mb-3 flex items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="text-sm font-semibold tracking-tight text-ink">{title}</h3>
          {description && <p className="mt-0.5 text-[11px] text-muted">{description}</p>}
          {library && (
            <p className="mt-1 font-mono text-[10px] uppercase tracking-wide text-faint">
              {library}
            </p>
          )}
        </div>
        <div className="flex shrink-0 gap-1">
          <Button
            variant="ghost"
            size="icon"
            title="Re-render chart"
            aria-label={`Re-render ${title}`}
            onClick={fetchChart}
          >
            <RefreshIcon size={15} />
          </Button>
          {url && (
            <a
              href={url}
              download={`electroshop-${slug}.png`}
              title="Download PNG"
              aria-label={`Download ${title} as PNG`}
              className="flex h-9 w-9 items-center justify-center rounded-[10px] text-muted transition-colors hover:bg-raised hover:text-ink"
            >
              <DownloadIcon size={15} />
            </a>
          )}
        </div>
      </div>

      <div
        className={cx(
          "flex flex-1 items-center justify-center overflow-hidden rounded-[10px] border border-line bg-app"
        )}
        style={{ minHeight: height }}
      >
        {state === "loading" && <Skeleton className="h-full w-full" style={{ minHeight: height }} />}

        {state === "error" && (
          <div className="flex flex-col items-center gap-2 px-6 py-8 text-center">
            <AlertIcon size={20} className="text-negative" />
            <p className="text-xs text-muted">{error}</p>
            <Button variant="secondary" size="sm" onClick={fetchChart}>
              Try again
            </Button>
          </div>
        )}

        {state === "ready" && url && (
          /* eslint-disable-next-line @next/next/no-img-element -- blob URL, not a remote asset */
          <img
            src={url}
            alt={`${title} — generated by Matplotlib and Seaborn on the server`}
            className="h-auto w-full max-w-full object-contain"
          />
        )}
      </div>
    </div>
  );
}
